# Generated by Django 4.2.11 on 2024-05-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
